= Ingo: A static site generator built on http://asciidoctor.org/[Asciidoctor]

image:https://badge.fury.io/rb/ingo.svg["Gem Version", link="https://badge.fury.io/rb/ingo"]

Ingo converts AsciiDoc files in a directory and converts them using http://asciidoctor.org/[Asciidoctor].
It is built for collecting notes in AciiDoc format and presenting them.

It is recommended to add `topics` to each file.

For example

----
:topics: gardening, hobby, shopping
----

defines three topics.
Ingo will create an index file for each topic linking to all documents with that topic.
Think of topics as "Categories" in wikipedia.
Ingo is meant to provide an alternative to wikis for note taking for individuals and teams.
In combination with Github/Gitlab and a CI service it can provide a similar experience for technical users.

Note that the files *must* be in a `docs` subdirectory of the project directory.
The resulting files are written to `output`.
An example project can be found at https://gitlab.com/fwilhe/berlin.

== How to build

.Install dependencies
----
bundle install
----

.Run tests
----
bundle exec rake test
----

== How to run

.Run program
----
bin/ingo path
----

== The name

Yes, I was thinking about https://gohugo.io/[Hugo] and just took another male name.

== Release process

This is still work in progress.
It needs automation wherever possible.

* Update changelog for upcoming release
* Remove `.unreleased` suffix from version and commit as "prepare release"
* `bundle exec rake release` (Creates and pushes the git tag and releases the artifact to ruby gems)
* Update version and append `.unreleased` and commit as "prepare for next development iteration"
