= Ingo: A static site generator built on http://asciidoctor.org/[Asciidoctor]

image:https://badge.fury.io/rb/ingo.svg["Gem Version", link="https://badge.fury.io/rb/ingo"]

Ingo converts AsciiDoc files in a directory to HTML using http://asciidoctor.org/[Asciidoctor] and creates index files.
It is built for collecting notes in AciiDoc format and presenting them.

If you are looking for a general purpose static site generator, I recommend looking at https://jekyllrb.com/[Jekyll] or https://gohugo.io/[Hugo].

== Usage

Ingo operates on a directory.
It takes all `*.adoc` files inside the `docs` directory into account and writes `*.html` files to `output`.

.Run Ingo
----
ingo path/to/my/notes
----

It is recommended to add `topics` to each file.

For example

----
:topics: gardening, hobby, shopping
----

defines three topics.
Ingo will create an index file for each topic linking to all documents with that topic.
Think of topics as "Categories" in a wiki.
Ingo is meant to provide an alternative to wikis for note taking for individuals and teams.
In combination with Github/Gitlab and a CI service it can provide a similar experience for technical users.

An example project can be found at https://gitlab.com/fwilhe/berlin.

== How to build

.Install dependencies
----
bundle install
----

.Run tests
----
bundle exec rake test
----

== Docker

It is also possible to use ingo in a container

.Example command to run ingo in Docker
----
docker run -v /path/to/docs:/documents/ registry.gitlab.com/fwilhe/ingo/image ingo .
----

== The name

Yes, I was thinking about https://gohugo.io/[Hugo] and just took another male name.

== Release process

This is still work in progress.
It needs automation wherever possible.

* Update changelog for upcoming release
* Remove `.unreleased` suffix from version and commit as "prepare release"
* `bundle exec rake release` (Creates and pushes the git tag and releases the artifact to ruby gems)
* Update version and append `.unreleased` and commit as "prepare for next development iteration"
