name: Build + Publish

on: [push]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Run Tests
      run: |
        bundle install
        bundle exec rake test

    - name: Publish to GPR
      if: github.ref == 'refs/heads/master'
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.GPR_AUTH_TOKEN}}
        OWNER: fwilhe2

    - name: Build and Publish Docker Image
      if: github.ref == 'refs/heads/master'
      run: |
        echo ${GPR_AUTH_TOKEN} | docker login docker.pkg.github.com -u ${OWNER} --password-stdin
        bundle exec rake push_docker_image
      env:
        GPR_AUTH_TOKEN: ${{secrets.GPR_AUTH_TOKEN}}
        OWNER: fwilhe2